"""
Django settings for PetCare project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment; falls back to dev key only if not provided.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-mb^z49#7d*vs!9s_9t@nj@n%oynwe=hzbzp5^l6xm1skrvdstr')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

# Hosts allowed in production (comma-separated env or default empty)
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if os.getenv('DJANGO_ALLOWED_HOSTS') else []

# CSRF trusted origins (required when using HTTPS or a reverse proxy)
CSRF_TRUSTED_ORIGINS = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS') else []

# ----- Development defaults (do not remove; useful for quick local runs) -----
# SECRET_KEY = 'django-insecure-mb^z49#7d*vs!9s_9t@nj@n%oynwe=hzbzp5^l6xm1skrvdstr'
# DEBUG = True
# ALLOWED_HOSTS = []
# CSRF_TRUSTED_ORIGINS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'PetApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Enable WhiteNoise to serve static files in production (optional, can rely on Nginx instead)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'PetCare.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PetCare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'PetApp.context_processors.nav_counters',
                'PetApp.context_processors.user_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'PetCare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'petcare_database'),
        'USER': os.getenv('DB_USER', 'petcare-administrator'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'root123'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

# Development database example (commented for safety):
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'petcare_database',
#         'USER': 'petcare-administrator',
#         'PASSWORD': 'root123',
#         'HOST': 'localhost',
#         'PORT': '5432',
#         'OPTIONS': { 'client_encoding': 'UTF8' },
#     }
# }

# NAME: petcare_database,
# USER': petcare-administrator,          
# PASSWORD': root123,



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Include the project-level static directory (PetCare/static)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Where collectstatic will place files for production serving
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise static files compression/storage
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Development static alternative (if you ever want to disable WhiteNoise):
# Remove WhiteNoise middleware above and use Nginx to serve STATIC_ROOT.

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
# URL name to redirect users to when login is required
LOGIN_URL = 'login'
# Where to go after successful login/logout
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'index'

# Rutas exentas de autenticación (regex relativas, sin prefijo '/')
# Rutas exentas de autenticación (regex relativas, sin prefijo '/')
LOGIN_EXEMPT_URLS = [
    r'^accounts/login/$',           # Login
    r'^accounts/logout/$',          # Logout
    r'^password_reset/',            # Recuperación de contraseña
    r'^reset/',                     # Reset de contraseña
    r'^password_reset/done/',       # Confirmación de recuperación
    r'^admin/',                     # Panel de administración
    
    # NUEVAS EXENCIONES PARA REGISTRO
    r'^accounts/registro/usuario/$', # Registro de usuario normal
    r'^accounts/registro/admin/$',   # Registro de administrador
]

# Email backend para desarrollo (mostrar emails por consola)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Session behavior: expire when the browser closes so users must log in again
# https://docs.djangoproject.com/en/stable/topics/http/sessions/#browser-length-sessions
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Optional: do NOT refresh the expiry on every request (keeps behavior predictable)
SESSION_SAVE_EVERY_REQUEST = False

# Security best practices for production
SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'False').lower() in ('1', 'true', 'yes')
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() in ('1', 'true', 'yes')
SECURE_HSTS_PRELOAD = os.getenv('DJANGO_SECURE_HSTS_PRELOAD', 'False').lower() in ('1', 'true', 'yes')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = os.getenv('DJANGO_SESSION_COOKIE_SECURE', 'False').lower() in ('1', 'true', 'yes')
CSRF_COOKIE_SECURE = os.getenv('DJANGO_CSRF_COOKIE_SECURE', 'False').lower() in ('1', 'true', 'yes')
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
