# Generated by Django 5.2.7 on 2025-11-02 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_producto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('especie', models.CharField(blank=True, max_length=30, null=True)),
                ('raza', models.CharField(blank=True, max_length=30, null=True)),
                ('nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id_propietario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_historial', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('tratamientos', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='DatosConsulta',
            fields=[
                ('id_consulta', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('detalles_paciente', models.TextField(blank=True, null=True)),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=30, null=True)),
                ('id_propietario', models.ForeignKey(db_column='id_propietario', on_delete=django.db.models.deletion.CASCADE, to='home.propietario')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_propietario',
            field=models.ForeignKey(db_column='id_propietario', on_delete=django.db.models.deletion.CASCADE, to='home.propietario'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_propietario', models.ForeignKey(db_column='id_propietario', on_delete=django.db.models.deletion.CASCADE, to='home.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='AseoMascota',
            fields=[
                ('id_aseo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tipo_banio', models.CharField(blank=True, choices=[('BASICO', 'Básico'), ('COMPLETO', 'Completo'), ('PREMIUM', 'Premium')], max_length=15, null=True)),
                ('es_agresivo', models.BooleanField(default=False)),
                ('fecha_banio', models.DateField(blank=True, null=True)),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
                ('id_propietario', models.ForeignKey(db_column='id_propietario', on_delete=django.db.models.deletion.CASCADE, to='home.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id_vacunacion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('veterinario', models.CharField(blank=True, max_length=30, null=True)),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
                ('id_vacuna', models.ForeignKey(db_column='id_vacuna', on_delete=django.db.models.deletion.CASCADE, to='home.vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('habitacion', models.CharField(blank=True, max_length=30, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_egreso__gte', models.F('fecha_ingreso'))), name='chk_fechas_hotel')],
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='home.factura')),
                ('id_pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, to='home.pago')),
            ],
            options={
                'unique_together': {('id_pago', 'id_factura')},
            },
        ),
        migrations.CreateModel(
            name='FacturaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('id_factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='home.factura')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, to='home.servicio')),
            ],
            options={
                'unique_together': {('id_factura', 'id_servicio')},
            },
        ),
    ]
