# Generated by Django 5.2.7 on 2025-11-08 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización'), ('VENTA', 'Venta'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Cantidad modificada (negativa para reducción)')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('source', models.CharField(blank=True, help_text='Origen lógico: vista, proceso, etc.', max_length=30, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='PetApp.producto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Cantidad mínima antes de alertar bajo stock')),
                ('expiration_date', models.DateField(blank=True, help_text='Fecha de caducidad (opcional)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='PetApp.producto')),
            ],
        ),
    ]
