# Generated by Django 5.2.7 on 2025-11-09 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0002_inventorymovement_productmeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Fecha de la cita')),
                ('hora', models.TimeField(help_text='Hora de inicio')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, help_text='Duración estimada en minutos')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PENDIENTE', max_length=15)),
                ('motivo', models.TextField(blank=True, help_text='Motivo o descripción de la cita', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, help_text='Veterinario o empleado asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PetApp.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='PetApp.pacientes')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PetApp.servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora'],
                'indexes': [models.Index(fields=['fecha', 'hora'], name='PetApp_cita_fecha_673825_idx'), models.Index(fields=['estado'], name='PetApp_cita_estado_f48064_idx')],
            },
        ),
    ]
